apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: http-metrics-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: http-metrics-app
  endpoints:
  - port: 3000
    path: /metrics

