apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-metrics-app
  template:
    metadata:
      labels:
        app: http-metrics-app
    spec:
      containers:
      - name: http-metrics-app
        image: <your-dockerhub-username>/http-metrics-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: http-metrics-service
spec:
  selector:
    app: http-metrics-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
